
const actions = {
    FETCH_WORD_SUCCESS: 'FETCH_WORD_SUCCESS',
    CHANGE_ACTIVE_LETTER: 'CHANGE_ACTIVE_LETTER',
    CHANGE_ACTIVE_MODE: 'CHANGE_ACTIVE_MODE',
    CHANGE_WORD_VALUE: 'CHANGE_WORD_VALUE',
    FETCH_WORD_ERROR: 'FETCH_WORD_ERROR',
    NO_ACTION_MATCH: 'NO_ACTION_MATCH'
}

export default actions